name = "my-astro-app"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-07-31"
compatibility_flags = [ "nodejs_compat" ]

[assets]
binding = "ASSETS"
directory = "./dist/"
not_found_handling = "404-page"

[observability]
enabled = true